dereuromark/cakephp-tools

- Model/Behavior/RevisionBehavior.php
ID has been fixed and committed so by specifying a fixed.
Thank you.
> Modified since ID is had been specified in fixed

- src/Auth/AuthUserTrait.php
Example for usage with roles defined in configuration file (non-db soles setup)
> added info to doku

- docs/Behavior/Passwordable.md
corrected fieldList usage in "Edit" example
> Updated Passwordable doku

- src/Model/Behavior/JsonableBehavior.php
- tests/TestCase/Model/Behavior/JsonableBehaviorTest.php
Fixes https://github.com/dereuromark/cakephp-tools/issues/153
> Fix Jsonable with find(list)

- src/Model/Behavior/SluggedBehavior.php
- tests/TestCase/Model/Behavior/SluggedBehaviorTest.php
Resolves https://github.com/dereuromark/cakephp-tools/issues/152
> Fix SluggedBehavior with multiple labels.

- docs/Behavior/Jsonable.md
- docs/Behavior/Passwordable.md
- docs/Behavior/Reset.md
- docs/Behavior/Slugged.md
Sorry to be late, I hadn't enough free time , and still don't
> Improve Behavior docs

- composer.json
- src/Utility/Utility.php
- tests/TestCase/Utility/UtilityTest.php
When trimming null values by default should stay null values.
> Fix trimDeep()

- src/Utility/Language.php
Feel free to discard it, that where the only nit-pickings I found.
> Readability / better practise (no CS)

- tests/TestCase/Utility/LanguageTest.php
Tests for PR #188
Sorry about the process. Next time I will do it from a feature branch.
> Add tests for PR #188

- docs/Error/ErrorHandler.md
- src/Error/ErrorHandler.php
- src/Error/ErrorHandlerTrait.php
- src/Error/Middleware/ErrorHandlerMiddleware.php
- tests/TestCase/Controller/ControllerTest.php
- tests/TestCase/Error/Middleware/ErrorHandlerMiddlewareTest.php
Those should not be moved into 404 log with the rest, since those are internally caused errors through faulty URLs on the page.
//cc @inoas
> Fix up internal 404s and consolidate via trait

- src/Mailer/Email.php
> Fix email attachments via https

- src/Mailer/Email.php
> Double base64 encoding fix

- src/Model/Behavior/PasswordableBehavior.php
Minimal change: fix deprecation warning for validator function.
> Change validator function to getValidator

- .travis.yml
- composer.json
- docs/Helper/Tree.md
- docs/README.md
- src/Model/Behavior/TypeMapBehavior.php
- src/View/Helper/TreeHelper.php
- tests/Fixture/DataFixture.php
- tests/TestCase/Model/Behavior/TypeMapBehaviorTest.php
- tests/TestCase/View/Helper/TreeHelperTest.php
- tests/test_app/Model/Table/DataTable.php
Reactivate Tree to have entity object support.
> Add tree parent info and add TypeMap behavior.

- src/Model/Behavior/ResetBehavior.php
- tests/TestCase/HtmlDom/HtmlDomTest.php
> Fix PHP7.3 tests.

- Model/Behavior/WhoDidItBehavior.php
This makes it compatible with Shim plugin
> Pass model id to exists method

- composer.json
- src/Controller/Component/CommonComponent.php
- src/Controller/Component/MobileComponent.php
- src/Controller/Component/UrlComponent.php
- src/Controller/ShuntRequestController.php
- src/Mailer/Email.php
> Updating src files

- tests/TestCase/Auth/MultiColumnAuthenticateTest.php
- tests/TestCase/Controller/Component/CommonComponentTest.php
- tests/TestCase/Controller/Component/MobileComponentTest.php
- tests/TestCase/Controller/Component/UrlComponentTest.php
- tests/TestCase/Controller/ControllerTest.php
- tests/TestCase/Form/ContactFormTest.php
- tests/TestCase/Mailer/EmailTest.php
- tests/TestCase/Model/Behavior/BitmaskedBehaviorTest.php
- tests/TestCase/Model/Behavior/ConfirmableBehaviorTest.php
- tests/TestCase/Model/Behavior/JsonableBehaviorTest.php
- tests/TestCase/Model/Behavior/NeighborBehaviorTest.php
- tests/TestCase/Model/Behavior/PasswordableBehaviorTest.php
- tests/TestCase/Model/Behavior/ResetBehaviorTest.php
- tests/TestCase/Model/Behavior/SluggedBehaviorTest.php
- tests/TestCase/Model/Behavior/StringBehaviorTest.php
- tests/TestCase/Model/Behavior/ToggleBehaviorTest.php
- tests/TestCase/Model/Behavior/TypeMapBehaviorTest.php
- tests/TestCase/Model/Behavior/TypographicBehaviorTest.php
- tests/TestCase/Model/Entity/EntityTest.php
- tests/TestCase/Model/Table/TableTest.php
- tests/TestCase/Model/Table/TokensTableTest.php
- tests/TestCase/View/Helper/HtmlHelperTest.php
- tests/TestCase/View/Helper/TreeHelperTest.php
- tests/TestCase/View/Helper/UrlHelperTest.php
- tests/bootstrap.php
> Fixing deprecations in TestCases

- src/Controller/Component/CommonComponent.php
- tests/TestCase/Controller/Component/CommonComponentTest.php
> Updating trim on posted data to be compatible with CakePHP 3.7+

- config/bootstrap.php
Cake tests throw an exception incase constants or functions are already defined.
> Fix exceptions while running cake tests

- src/Utility/Utility.php
- tests/TestCase/Utility/UtilityTest.php
> Fixing issue where ints are casted to strings

- src/Model/Behavior/BitmaskedBehavior.php
> BitmaskedBehavior mappedField field validation fix

- README.md
- docs/Helper/Meter.md
- docs/Helper/Progress.md
- docs/README.md
- src/View/Helper/MeterHelper.php
- src/View/Helper/ProgressHelper.php
- tests/TestCase/View/Helper/MeterHelperTest.php
> Add meter bar.

- .travis.yml
requires first CakePHP 3.8.2 release
> Check PHP74

- docs/Component/RefererRedirect.md
- src/Controller/Component/RefererRedirectComponent.php
- tests/TestCase/Controller/Component/RefererRedirectComponentTest.php
- tests/TestCase/Model/Behavior/TypographicBehaviorTest.php
- tests/test_app/Controller/RefererRedirectComponentTestController.php
WIP
maybe someone can add some tests and more docs/examples?
> Add RefererRedirect component.

- src/View/Helper/GravatarHelper.php
- tests/TestCase/View/Helper/GravatarHelperTest.php
Resolves https://github.com/dereuromark/cakephp-tools/issues/246
Added actual useful tests.
> Fix Avatar escaping

- phpunit.xml.dist
- src/Model/Behavior/PasswordableBehavior.php
- src/Model/Table/TokensTable.php
> Remove deprecations

- .gitignore
- docs/README.md
- docs/Utility/FileLog.md
- src/Utility/FileLog.php
- tests/TestCase/Utility/FileLogTest.php
- tests/bootstrap.php
> Add custom log class for CakePHP 4

- src/View/Helper/TimeHelper.php
See https://github.com/dereuromark/cakephp-queue/issues/346
> use FrozenTime instead of Time utility inside TimeHelper

- .gitignore
- composer.json
- config/bootstrap.php
- phpunit.xml.dist
- tests/TestCase/View/Icon/Collector/FontAwesome4CollectorTest.php
- tests/bootstrap.php
- tests/test_app/Model/Table/DataTable.php
This plugin requires the shim plugin so we could indeed move the old `DAY` etc. constants into that but for now I have added them to the bootstrap of this plugin.
> cake5 upgrade

- src/Error/ErrorLogger.php
Resolve https://github.com/cakephp/cakephp/commit/c38f6ff6baa3ba357d025071ebd0a416704c3f22 for 5.1
> Fix upcoming method conflict

- src/Model/Table/Table.php
- tests/TestCase/Model/Behavior/PasswordableBehaviorTest.php
- tests/TestCase/Model/Table/TableTest.php
> Fix up Cake52 compat.

- composer.json
- docs/Authentication/LoginLink.md
- docs/README.md
- src/Authenticator/LoginLinkAuthenticator.php
- src/Identifier/LoginLinkIdentifier.php
- tests/TestCase/Authenticator/LoginLinkAuthenticatorTest.php
- tests/TestCase/Identifier/LoginLinkIdentifierTest.php
Simple login link authenticator for Tokens.
> Add LoginLinkAuthenticator

- src/View/Helper/TreeHelper.php
- tests/TestCase/View/Helper/TreeHelperTest.php
Refs https://github.com/cakephp/cakephp/pull/18683
> Add more stringable support for TreeHelper.
